INSERT INTO Ingredient (name, unitOfMeasure) VALUES
('Poisson haché', 'tasses'),
('Épinard en poudre', 'grammes'),
('Huile d''olive haché', 'ml'),
('Crème frais', 'cuillères'),
('Citron frais', 'millilitres'),
('Ail bio', 'litres'),
('Sucre', 'kg'),
('Poulet séché', 'cuillères'),
('Oignon', 'grammes'),
('Huile d''olive', 'litres'),
('Dinde en poudre', 'cuillères'),
('Huile d''olive bio', 'kg'),
('Champignon râpé', 'cuillères'),
('Pomme entier', 'litres'),
('Poivre', 'ml'),
('Tomate en poudre', 'unités'),
('Lait', 'grammes'),
('Poulet entier', 'ml'),
('Riz bio', 'litres'),
('Poisson râpé', 'grammes'),
('Oignon séché', 'unités'),
('Pâtes entier', 'ml'),
('Crème bio', 'tasses'),
('Épinard en poudre', 'cuillères'),
('Noix en poudre', 'unités'),
('Ail frais', 'litres'),
('Sucre', 'millilitres'),
('Persil', 'litres'),
('Pomme en poudre', 'grammes'),
('Riz haché', 'kg'),
('Champignon râpé', 'tasses'),
('Crème frais', 'litres'),
('Farine frais', 'litres'),
('Poisson entier', 'kg'),
('Boeuf râpé', 'ml'),
('Pâtes haché', 'tasses'),
('Riz bio', 'kg'),
('Thon râpé', 'unités'),
('Citron râpé', 'millilitres'),
('Banane râpé', 'litres'),
('Tomate haché', 'millilitres'),
('Sel haché', 'cuillères'),
('Poivre', 'millilitres'),
('Pâtes', 'ml'),
('Ail frais', 'grammes'),
('Poulet frais', 'litres'),
('Riz entier', 'millilitres'),
('Épinard bio', 'millilitres'),
('Persil entier', 'litres'),
('Ail', 'kg'),
('Poulet râpé', 'litres'),
('Poulet frais', 'litres'),
('Boeuf haché', 'litres'),
('Farine séché', 'grammes'),
('Lait séché', 'cuillères'),
('Sucre bio', 'cuillères'),
('Boeuf entier', 'kg'),
('Farine', 'tasses'),
('Thon', 'unités'),
('Pomme', 'cuillères'),
('Farine entier', 'cuillères'),
('Poulet séché', 'tasses'),
('Ail bio', 'litres'),
('Lait séché', 'grammes'),
('Pâtes en poudre', 'ml'),
('Huile d''olive haché', 'kg'),
('Persil entier', 'tasses'),
('Ail haché', 'unités'),
('Persil frais', 'tasses'),
('Citron bio', 'millilitres'),
('Carotte frais', 'tasses'),
('Pomme haché', 'millilitres'),
('Persil frais', 'grammes'),
('Pâtes en poudre', 'grammes'),
('Lait râpé', 'kg'),
('Citron bio', 'tasses'),
('Poivre frais', 'unités'),
('Beurre râpé', 'tasses'),
('Persil séché', 'grammes'),
('Poivre haché', 'millilitres'),
('Lait frais', 'ml'),
('Lait bio', 'unités'),
('Dinde séché', 'cuillères'),
('Lait', 'ml'),
('Banane en poudre', 'ml'),
('Thon séché', 'millilitres'),
('Champignon', 'litres'),
('Beurre bio', 'grammes'),
('Huile d''olive bio', 'cuillères'),
('Tomate bio', 'ml'),
('Pomme séché', 'grammes'),
('Dinde bio', 'tasses'),
('Oignon bio', 'unités'),
('Poulet', 'unités'),
('Riz séché', 'cuillères'),
('Carotte entier', 'kg'),
('Poulet râpé', 'grammes'),
('Citron haché', 'cuillères'),
('Poisson haché', 'millilitres'),
('Poulet en poudre', 'kg'),
('Farine haché', 'grammes'),
('Champignon frais', 'cuillères'),
('Crème râpé', 'millilitres'),
('Farine entier', 'millilitres'),
('Boeuf', 'millilitres'),
('Noix bio', 'millilitres'),
('Farine', 'ml'),
('Pâtes', 'litres'),
('Pâtes haché', 'kg'),
('Noix râpé', 'kg'),
('Crème frais', 'grammes'),
('Sel entier', 'millilitres'),
('Pâtes en poudre', 'tasses'),
('Carotte frais', 'grammes'),
('Noix en poudre', 'cuillères'),
('Tomate', 'cuillères'),
('Riz entier', 'kg'),
('Carotte bio', 'millilitres'),
('Dinde bio', 'litres'),
('Pâtes en poudre', 'litres'),
('Sel râpé', 'litres'),
('Pomme haché', 'litres'),
('Sucre séché', 'grammes'),
('Tomate', 'tasses'),
('Oignon bio', 'unités'),
('Pomme haché', 'tasses'),
('Tomate râpé', 'kg'),
('Sucre haché', 'unités'),
('Poulet entier', 'kg'),
('Ail séché', 'unités'),
('Crème râpé', 'cuillères'),
('Lait entier', 'kg'),
('Poulet haché', 'grammes'),
('Pomme râpé', 'millilitres'),
('Ail bio', 'ml'),
('Poisson', 'cuillères'),
('Champignon en poudre', 'litres'),
('Huile d''olive râpé', 'ml'),
('Noix haché', 'ml'),
('Boeuf entier', 'litres'),
('Lait bio', 'cuillères'),
('Pâtes', 'ml'),
('Thon haché', 'cuillères'),
('Persil haché', 'tasses'),
('Riz entier', 'kg'),
('Oignon en poudre', 'grammes'),
('Carotte en poudre', 'unités'),
('Poivre séché', 'millilitres'),
('Poulet', 'litres'),
('Lait bio', 'millilitres'),
('Citron haché', 'kg'),
('Poivre frais', 'litres'),
('Oignon en poudre', 'cuillères'),
('Beurre', 'millilitres'),
('Thon en poudre', 'unités'),
('Farine', 'unités'),
('Huile d''olive séché', 'unités'),
('Pâtes bio', 'kg'),
('Crème en poudre', 'millilitres'),
('Sel', 'unités'),
('Sucre râpé', 'ml'),
('Ail râpé', 'millilitres'),
('Pomme frais', 'litres'),
('Farine râpé', 'kg'),
('Pomme bio', 'kg'),
('Pomme haché', 'litres'),
('Persil', 'unités'),
('Sel en poudre', 'unités'),
('Riz frais', 'millilitres'),
('Poivre en poudre', 'unités'),
('Lait en poudre', 'ml'),
('Poivre séché', 'kg'),
('Carotte bio', 'cuillères'),
('Champignon frais', 'unités'),
('Carotte séché', 'ml'),
('Épinard râpé', 'kg'),
('Huile d''olive séché', 'kg'),
('Champignon frais', 'litres'),
('Tomate haché', 'litres'),
('Sucre séché', 'tasses'),
('Carotte entier', 'tasses'),
('Champignon frais', 'millilitres'),
('Tomate haché', 'tasses'),
('Sel frais', 'cuillères'),
('Épinard bio', 'cuillères'),
('Poisson bio', 'tasses'),
('Lait bio', 'unités'),
('Poisson', 'tasses'),
('Oignon séché', 'ml'),
('Thon', 'ml'),
('Noix frais', 'tasses'),
('Beurre bio', 'cuillères'),
('Thon séché', 'unités'),
('Poisson entier', 'ml'),
('Beurre haché', 'kg'),
('Tomate entier', 'millilitres'),
('Riz en poudre', 'cuillères'),
('Carotte haché', 'tasses'),
('Poivre entier', 'ml'),
('Oignon séché', 'kg'),
('Carotte bio', 'unités'),
('Poulet entier', 'grammes'),
('Banane séché', 'kg'),
('Champignon bio', 'millilitres'),
('Oignon entier', 'litres'),
('Carotte entier', 'ml'),
('Poisson séché', 'grammes'),
('Huile d''olive', 'cuillères'),
('Ail haché', 'cuillères'),
('Banane râpé', 'kg'),
('Citron haché', 'tasses'),
('Champignon', 'millilitres'),
('Oignon entier', 'grammes'),
('Carotte séché', 'litres'),
('Boeuf', 'litres'),
('Beurre', 'kg'),
('Poisson entier', 'cuillères'),
('Ail haché', 'millilitres'),
('Pomme séché', 'kg'),
('Épinard haché', 'millilitres'),
('Pâtes séché', 'kg'),
('Thon entier', 'litres'),
('Sel', 'millilitres'),
('Sucre', 'cuillères'),
('Dinde', 'ml'),
('Crème entier', 'unités'),
('Oignon', 'unités'),
('Sucre bio', 'cuillères'),
('Sucre râpé', 'ml'),
('Poisson haché', 'unités'),
('Thon bio', 'millilitres'),
('Pâtes séché', 'cuillères'),
('Sel séché', 'unités'),
('Crème frais', 'grammes'),
('Farine entier', 'kg'),
('Champignon haché', 'cuillères'),
('Boeuf frais', 'kg'),
('Épinard haché', 'millilitres'),
('Sel frais', 'millilitres'),
('Tomate', 'ml'),
('Ail en poudre', 'cuillères'),
('Dinde frais', 'litres'),
('Épinard râpé', 'kg'),
('Farine frais', 'grammes'),
('Ail séché', 'grammes'),
('Ail bio', 'ml'),
('Épinard bio', 'kg'),
('Poulet râpé', 'tasses'),
('Banane râpé', 'litres'),
('Persil râpé', 'unités'),
('Épinard bio', 'tasses'),
('Poisson haché', 'tasses'),
('Beurre séché', 'unités'),
('Farine râpé', 'cuillères'),
('Sucre séché', 'litres'),
('Pâtes en poudre', 'unités'),
('Boeuf', 'tasses'),
('Crème en poudre', 'tasses'),
('Lait frais', 'grammes'),
('Dinde haché', 'tasses'),
('Champignon haché', 'grammes'),
('Oignon entier', 'cuillères'),
('Lait haché', 'kg'),
('Thon en poudre', 'cuillères'),
('Crème en poudre', 'kg'),
('Banane', 'litres'),
('Huile d''olive séché', 'cuillères'),
('Sel entier', 'kg'),
('Thon en poudre', 'ml'),
('Sucre entier', 'unités'),
('Pâtes bio', 'ml'),
('Thon bio', 'grammes'),
('Farine râpé', 'millilitres'),
('Noix entier', 'litres'),
('Poisson frais', 'millilitres'),
('Poulet entier', 'grammes'),
('Carotte frais', 'cuillères'),
('Boeuf en poudre', 'unités'),
('Noix bio', 'unités'),
('Banane râpé', 'grammes'),
('Huile d''olive entier', 'cuillères'),
('Ail bio', 'cuillères'),
('Champignon frais', 'cuillères'),
('Crème', 'grammes'),
('Citron', 'cuillères'),
('Dinde bio', 'cuillères'),
('Sel en poudre', 'grammes'),
('Poulet entier', 'kg'),
('Riz bio', 'litres'),
('Citron bio', 'kg'),
('Banane', 'ml'),
('Pomme haché', 'litres'),
('Carotte entier', 'tasses'),
('Carotte entier', 'tasses'),
('Pomme', 'unités'),
('Pâtes haché', 'kg'),
('Ail haché', 'millilitres'),
('Persil frais', 'unités'),
('Pâtes frais', 'grammes'),
('Champignon', 'grammes'),
('Pomme séché', 'tasses'),
('Farine entier', 'kg'),
('Lait entier', 'ml'),
('Pomme frais', 'unités'),
('Noix entier', 'unités'),
('Boeuf', 'tasses'),
('Tomate frais', 'ml'),
('Banane', 'unités'),
('Riz en poudre', 'cuillères'),
('Épinard frais', 'litres'),
('Poisson bio', 'ml'),
('Boeuf bio', 'litres'),
('Banane haché', 'ml'),
('Pâtes entier', 'cuillères'),
('Poulet en poudre', 'ml'),
('Thon en poudre', 'unités'),
('Noix en poudre', 'kg'),
('Thon en poudre', 'kg'),
('Boeuf entier', 'ml'),
('Ail en poudre', 'cuillères'),
('Riz', 'grammes'),
('Farine haché', 'cuillères'),
('Poisson bio', 'tasses'),
('Champignon haché', 'ml'),
('Dinde', 'millilitres'),
('Sucre frais', 'kg'),
('Pomme râpé', 'tasses'),
('Crème en poudre', 'ml'),
('Huile d''olive râpé', 'kg'),
('Persil râpé', 'millilitres'),
('Boeuf haché', 'cuillères'),
('Crème frais', 'grammes'),
('Poulet frais', 'unités'),
('Tomate', 'tasses'),
('Sel en poudre', 'millilitres'),
('Ail frais', 'unités'),
('Crème râpé', 'tasses'),
('Oignon frais', 'millilitres'),
('Beurre séché', 'litres'),
('Sucre râpé', 'tasses'),
('Persil frais', 'cuillères'),
('Ail séché', 'unités'),
('Riz en poudre', 'kg'),
('Dinde séché', 'unités'),
('Beurre séché', 'cuillères'),
('Riz bio', 'litres'),
('Dinde en poudre', 'cuillères'),
('Oignon frais', 'unités'),
('Noix bio', 'kg'),
('Carotte séché', 'litres'),
('Citron entier', 'tasses'),
('Riz haché', 'millilitres'),
('Persil entier', 'cuillères'),
('Pâtes frais', 'millilitres'),
('Persil', 'cuillères'),
('Beurre râpé', 'unités'),
('Poivre séché', 'ml'),
('Pâtes haché', 'cuillères'),
('Crème en poudre', 'cuillères'),
('Farine', 'millilitres'),
('Boeuf entier', 'millilitres'),
('Boeuf râpé', 'ml'),
('Poulet râpé', 'cuillères'),
('Champignon en poudre', 'litres'),
('Poisson entier', 'millilitres'),
('Farine bio', 'litres'),
('Dinde haché', 'tasses'),
('Sel entier', 'grammes'),
('Crème haché', 'grammes'),
('Noix frais', 'cuillères'),
('Riz séché', 'unités'),
('Sel en poudre', 'litres'),
('Dinde haché', 'ml'),
('Tomate frais', 'kg'),
('Noix frais', 'grammes'),
('Tomate haché', 'cuillères'),
('Épinard frais', 'millilitres'),
('Sel', 'tasses'),
('Citron', 'litres'),
('Riz haché', 'litres'),
('Pomme haché', 'kg'),
('Lait séché', 'ml'),
('Poulet', 'ml'),
('Épinard séché', 'litres'),
('Épinard frais', 'litres'),
('Dinde râpé', 'kg'),
('Boeuf bio', 'ml'),
('Sel en poudre', 'millilitres'),
('Sucre bio', 'millilitres'),
('Boeuf râpé', 'ml'),
('Pâtes bio', 'millilitres'),
('Noix en poudre', 'kg'),
('Sucre en poudre', 'grammes'),
('Citron haché', 'millilitres'),
('Thon râpé', 'unités'),
('Thon râpé', 'cuillères'),
('Lait séché', 'grammes'),
('Tomate frais', 'tasses'),
('Noix frais', 'cuillères'),
('Poivre frais', 'litres'),
('Boeuf bio', 'kg'),
('Beurre entier', 'grammes'),
('Champignon séché', 'cuillères'),
('Dinde bio', 'tasses'),
('Sucre bio', 'grammes'),
('Épinard râpé', 'ml'),
('Épinard râpé', 'cuillères'),
('Poisson frais', 'millilitres'),
('Noix séché', 'ml'),
('Beurre entier', 'ml'),
('Lait entier', 'grammes'),
('Champignon râpé', 'kg'),
('Banane frais', 'grammes'),
('Ail', 'cuillères'),
('Épinard entier', 'litres'),
('Noix râpé', 'kg'),
('Poivre séché', 'tasses'),
('Crème frais', 'unités'),
('Banane séché', 'litres'),
('Riz frais', 'unités'),
('Boeuf bio', 'grammes'),
('Beurre râpé', 'grammes'),
('Poivre entier', 'ml'),
('Tomate frais', 'ml'),
('Poisson frais', 'millilitres'),
('Crème râpé', 'litres'),
('Tomate séché', 'tasses'),
('Sucre', 'millilitres'),
('Poulet entier', 'kg'),
('Ail entier', 'unités'),
('Boeuf bio', 'kg'),
('Carotte', 'tasses'),
('Riz haché', 'millilitres'),
('Beurre séché', 'grammes'),
('Crème bio', 'cuillères'),
('Oignon', 'millilitres'),
('Citron entier', 'litres'),
('Sucre bio', 'cuillères'),
('Riz frais', 'tasses'),
('Tomate bio', 'litres'),
('Pâtes bio', 'tasses'),
('Banane', 'litres'),
('Carotte entier', 'cuillères'),
('Beurre en poudre', 'cuillères'),
('Thon en poudre', 'unités'),
('Épinard', 'litres'),
('Citron entier', 'litres'),
('Lait', 'litres'),
('Sucre râpé', 'tasses'),
('Boeuf séché', 'tasses'),
('Ail frais', 'kg'),
('Épinard frais', 'grammes'),
('Lait séché', 'tasses'),
('Riz bio', 'grammes'),
('Lait en poudre', 'cuillères'),
('Citron haché', 'kg'),
('Riz frais', 'litres'),
('Dinde râpé', 'cuillères'),
('Persil', 'grammes'),
('Thon séché', 'ml'),
('Sucre râpé', 'litres'),
('Sel entier', 'litres'),
('Dinde en poudre', 'tasses'),
('Sel séché', 'ml'),
('Épinard râpé', 'cuillères'),
('Pomme entier', 'litres'),
('Ail en poudre', 'kg'),
('Dinde haché', 'grammes'),
('Sel bio', 'kg'),
('Tomate', 'unités'),
('Oignon bio', 'kg'),
('Épinard séché', 'litres'),
('Poulet entier', 'tasses'),
('Poulet haché', 'kg'),
('Lait séché', 'tasses'),
('Noix en poudre', 'cuillères'),
('Crème en poudre', 'cuillères'),
('Poisson séché', 'tasses'),
('Farine frais', 'grammes'),
('Lait haché', 'litres'),
('Poisson haché', 'grammes'),
('Tomate séché', 'millilitres'),
('Champignon râpé', 'unités'),
('Citron râpé', 'unités'),
('Oignon bio', 'unités'),
('Champignon en poudre', 'millilitres'),
('Thon séché', 'kg'),
('Persil râpé', 'kg'),
('Sucre entier', 'kg'),
('Boeuf entier', 'grammes'),
('Thon séché', 'tasses'),
('Poivre séché', 'tasses'),
('Carotte haché', 'millilitres'),
('Épinard bio', 'ml'),
('Sucre séché', 'kg'),
('Riz', 'ml'),
('Banane en poudre', 'litres'),
('Persil bio', 'millilitres'),
('Ail en poudre', 'litres'),
('Poisson entier', 'unités'),
('Poivre râpé', 'litres'),
('Poulet', 'grammes'),
('Poisson entier', 'ml'),
('Pomme haché', 'kg'),
('Pâtes bio', 'millilitres'),
('Pomme', 'unités'),
('Poisson frais', 'ml'),
('Citron', 'cuillères'),
('Carotte frais', 'tasses'),
('Beurre frais', 'litres'),
('Dinde frais', 'cuillères'),
('Boeuf bio', 'cuillères'),
('Lait', 'unités'),
('Thon', 'unités'),
('Tomate entier', 'unités'),
('Boeuf haché', 'litres'),
('Boeuf entier', 'millilitres'),
('Champignon en poudre', 'millilitres'),
('Thon haché', 'cuillères'),
('Sel séché', 'cuillères'),
('Poivre haché', 'cuillères'),
('Pomme séché', 'ml'),
('Ail bio', 'kg'),
('Ail en poudre', 'tasses'),
('Pâtes râpé', 'kg'),
('Ail râpé', 'ml'),
('Noix', 'litres'),
('Beurre frais', 'grammes'),
('Carotte séché', 'grammes'),
('Champignon', 'litres'),
('Pâtes râpé', 'ml'),
('Dinde en poudre', 'tasses'),
('Champignon entier', 'litres'),
('Thon entier', 'ml'),
('Tomate râpé', 'litres'),
('Poivre bio', 'kg'),
('Épinard en poudre', 'cuillères'),
('Épinard entier', 'tasses'),
('Carotte frais', 'grammes'),
('Poisson bio', 'grammes'),
('Crème bio', 'litres'),
('Ail entier', 'kg'),
('Citron en poudre', 'grammes'),
('Lait en poudre', 'cuillères'),
('Noix frais', 'unités'),
('Huile d''olive frais', 'kg'),
('Poivre entier', 'grammes'),
('Beurre haché', 'tasses'),
('Thon râpé', 'cuillères'),
('Noix en poudre', 'millilitres'),
('Boeuf', 'grammes'),
('Crème frais', 'grammes'),
('Noix en poudre', 'grammes'),
('Citron frais', 'ml'),
('Persil râpé', 'ml'),
('Dinde bio', 'kg'),
('Huile d''olive', 'millilitres'),
('Persil', 'grammes'),
('Pâtes entier', 'litres'),
('Citron', 'grammes'),
('Thon entier', 'unités'),
('Champignon râpé', 'tasses'),
('Boeuf', 'cuillères'),
('Farine en poudre', 'litres'),
('Champignon râpé', 'ml'),
('Épinard entier', 'kg'),
('Poisson haché', 'millilitres'),
('Carotte bio', 'litres'),
('Poisson', 'grammes'),
('Banane frais', 'ml'),
('Riz frais', 'millilitres'),
('Poisson', 'ml'),
('Crème frais', 'millilitres'),
('Poulet bio', 'tasses'),
('Sel bio', 'ml'),
('Farine haché', 'unités'),
('Carotte haché', 'cuillères'),
('Riz bio', 'grammes'),
('Huile d''olive râpé', 'tasses'),
('Persil en poudre', 'litres'),
('Oignon séché', 'cuillères'),
('Persil râpé', 'kg'),
('Thon râpé', 'unités'),
('Ail entier', 'kg'),
('Persil', 'kg'),
('Beurre', 'tasses'),
('Banane frais', 'ml'),
('Noix frais', 'millilitres'),
('Huile d''olive râpé', 'ml'),
('Sel râpé', 'millilitres'),
('Crème', 'grammes'),
('Crème râpé', 'kg'),
('Sel', 'millilitres'),
('Champignon entier', 'ml'),
('Thon en poudre', 'grammes'),
('Épinard entier', 'ml'),
('Boeuf râpé', 'cuillères'),
('Crème haché', 'kg'),
('Citron râpé', 'tasses'),
('Farine bio', 'cuillères'),
('Beurre haché', 'unités'),
('Poisson séché', 'cuillères'),
('Poulet entier', 'tasses'),
('Dinde haché', 'unités'),
('Tomate bio', 'kg'),
('Champignon', 'grammes'),
('Pomme râpé', 'cuillères'),
('Épinard râpé', 'litres'),
('Beurre entier', 'grammes'),
('Pomme', 'kg'),
('Poivre entier', 'grammes'),
('Poulet en poudre', 'kg'),
('Pâtes haché', 'kg'),
('Riz bio', 'tasses'),
('Noix bio', 'grammes'),
('Boeuf', 'kg'),
('Persil en poudre', 'unités'),
('Lait râpé', 'kg'),
('Poivre en poudre', 'unités'),
('Thon râpé', 'millilitres'),
('Citron haché', 'ml'),
('Poulet séché', 'tasses'),
('Sel', 'cuillères'),
('Pâtes entier', 'tasses'),
('Citron', 'millilitres'),
('Huile d''olive frais', 'tasses'),
('Sucre haché', 'litres'),
('Sucre entier', 'tasses'),
('Huile d''olive bio', 'millilitres'),
('Carotte haché', 'unités'),
('Persil séché', 'ml'),
('Beurre bio', 'grammes'),
('Citron', 'tasses'),
('Pomme bio', 'litres'),
('Pomme entier', 'millilitres'),
('Poisson séché', 'grammes'),
('Sel entier', 'millilitres'),
('Sel', 'unités'),
('Poivre entier', 'cuillères'),
('Tomate frais', 'tasses'),
('Tomate frais', 'unités'),
('Sucre haché', 'kg'),
('Persil bio', 'grammes'),
('Dinde', 'kg'),
('Poisson en poudre', 'kg'),
('Sucre bio', 'ml'),
('Oignon râpé', 'tasses'),
('Carotte bio', 'litres'),
('Crème entier', 'millilitres'),
('Carotte séché', 'millilitres'),
('Pomme entier', 'kg'),
('Poivre râpé', 'grammes'),
('Oignon frais', 'litres'),
('Carotte entier', 'cuillères'),
('Noix', 'litres'),
('Pomme entier', 'litres'),
('Champignon séché', 'millilitres'),
('Carotte bio', 'unités'),
('Lait frais', 'tasses'),
('Poisson bio', 'unités'),
('Carotte séché', 'millilitres'),
('Banane râpé', 'cuillères'),
('Citron râpé', 'litres'),
('Farine entier', 'tasses'),
('Banane râpé', 'grammes'),
('Boeuf entier', 'millilitres'),
('Tomate bio', 'grammes'),
('Oignon haché', 'cuillères'),
('Ail frais', 'tasses'),
('Poivre en poudre', 'tasses'),
('Sel entier', 'kg'),
('Ail râpé', 'litres'),
('Carotte séché', 'kg'),
('Champignon râpé', 'grammes'),
('Pâtes haché', 'millilitres'),
('Oignon frais', 'tasses'),
('Pomme haché', 'kg'),
('Ail râpé', 'cuillères'),
('Farine en poudre', 'ml'),
('Banane bio', 'litres'),
('Farine en poudre', 'litres'),
('Dinde séché', 'kg'),
('Lait', 'unités'),
('Pâtes frais', 'tasses'),
('Ail', 'kg'),
('Ail frais', 'grammes'),
('Farine', 'ml'),
('Persil bio', 'grammes'),
('Persil entier', 'grammes'),
('Pomme râpé', 'tasses'),
('Sucre haché', 'unités'),
('Carotte', 'cuillères'),
('Sucre en poudre', 'kg'),
('Lait frais', 'kg'),
('Épinard entier', 'tasses'),
('Thon haché', 'tasses'),
('Pomme frais', 'millilitres'),
('Huile d''olive râpé', 'grammes'),
('Farine bio', 'tasses'),
('Huile d''olive en poudre', 'unités'),
('Poivre bio', 'unités'),
('Poisson entier', 'grammes'),
('Citron', 'cuillères'),
('Boeuf frais', 'kg'),
('Ail en poudre', 'cuillères'),
('Épinard bio', 'millilitres'),
('Champignon bio', 'ml'),
('Sel haché', 'grammes'),
('Sucre râpé', 'grammes'),
('Noix', 'millilitres'),
('Lait en poudre', 'grammes'),
('Riz haché', 'grammes'),
('Lait haché', 'kg'),
('Champignon bio', 'millilitres'),
('Boeuf râpé', 'grammes'),
('Noix râpé', 'millilitres'),
('Sucre séché', 'millilitres'),
('Riz séché', 'litres'),
('Poulet bio', 'millilitres'),
('Sel en poudre', 'grammes'),
('Sel séché', 'grammes'),
('Thon haché', 'litres'),
('Persil entier', 'cuillères'),
('Lait', 'litres'),
('Carotte en poudre', 'ml'),
('Farine bio', 'grammes'),
('Pâtes', 'kg'),
('Dinde râpé', 'litres'),
('Épinard bio', 'grammes'),
('Poulet râpé', 'kg'),
('Poivre frais', 'litres'),
('Pomme frais', 'cuillères'),
('Riz râpé', 'ml'),
('Farine bio', 'unités'),
('Dinde entier', 'millilitres'),
('Épinard', 'unités'),
('Ail en poudre', 'unités'),
('Crème en poudre', 'litres'),
('Lait haché', 'kg'),
('Tomate', 'ml'),
('Huile d''olive bio', 'unités'),
('Beurre', 'kg'),
('Sel bio', 'millilitres'),
('Poisson frais', 'ml'),
('Poisson râpé', 'kg'),
('Carotte séché', 'ml'),
('Noix entier', 'kg'),
('Farine haché', 'unités'),
('Banane bio', 'cuillères'),
('Pâtes râpé', 'ml'),
('Dinde frais', 'cuillères'),
('Lait séché', 'grammes'),
('Banane râpé', 'litres'),
('Crème séché', 'kg'),
('Beurre frais', 'cuillères'),
('Tomate en poudre', 'unités'),
('Riz en poudre', 'tasses'),
('Persil râpé', 'millilitres'),
('Pâtes bio', 'litres'),
('Sucre séché', 'grammes'),
('Huile d''olive', 'cuillères'),
('Noix frais', 'cuillères'),
('Riz bio', 'millilitres'),
('Pâtes entier', 'unités'),
('Beurre haché', 'tasses'),
('Carotte frais', 'cuillères'),
('Riz', 'grammes'),
('Sel frais', 'unités'),
('Pâtes frais', 'tasses'),
('Pomme séché', 'grammes'),
('Beurre entier', 'ml'),
('Poisson frais', 'unités'),
('Champignon en poudre', 'kg'),
('Crème râpé', 'grammes'),
('Champignon entier', 'millilitres'),
('Persil râpé', 'litres'),
('Beurre', 'grammes'),
('Beurre haché', 'unités'),
('Dinde frais', 'litres'),
('Épinard râpé', 'unités'),
('Persil', 'litres'),
('Citron entier', 'kg'),
('Ail haché', 'tasses'),
('Sucre', 'litres'),
('Banane haché', 'tasses'),
('Lait séché', 'grammes'),
('Tomate bio', 'ml'),
('Crème en poudre', 'kg'),
('Persil frais', 'cuillères'),
('Thon séché', 'litres'),
('Sucre haché', 'cuillères'),
('Farine bio', 'litres'),
('Pomme séché', 'kg'),
('Thon en poudre', 'kg'),
('Champignon frais', 'tasses'),
('Beurre en poudre', 'millilitres'),
('Tomate bio', 'ml'),
('Ail entier', 'tasses'),
('Sel râpé', 'kg'),
('Noix entier', 'millilitres'),
('Crème séché', 'grammes'),
('Pomme en poudre', 'unités'),
('Poisson séché', 'ml'),
('Sucre râpé', 'kg'),
('Citron séché', 'cuillères'),
('Tomate râpé', 'unités'),
('Poulet', 'kg'),
('Poisson bio', 'cuillères'),
('Oignon râpé', 'litres'),
('Champignon entier', 'tasses'),
('Champignon bio', 'ml'),
('Beurre séché', 'cuillères'),
('Banane bio', 'tasses'),
('Oignon bio', 'millilitres'),
('Banane séché', 'ml'),
('Ail', 'grammes'),
('Champignon entier', 'grammes'),
('Tomate séché', 'tasses'),
('Persil bio', 'unités'),
('Riz râpé', 'litres'),
('Poivre haché', 'tasses'),
('Banane râpé', 'ml'),
('Riz frais', 'millilitres'),
('Poulet bio', 'tasses'),
('Citron râpé', 'kg'),
('Noix entier', 'grammes'),
('Crème bio', 'kg'),
('Sucre bio', 'tasses'),
('Carotte râpé', 'millilitres'),
('Citron haché', 'litres'),
('Beurre séché', 'grammes'),
('Dinde bio', 'litres'),
('Ail', 'cuillères'),
('Pomme râpé', 'kg'),
('Pâtes', 'unités'),
('Poivre', 'cuillères'),
('Ail', 'kg'),
('Banane haché', 'millilitres'),
('Huile d''olive frais', 'cuillères'),
('Thon haché', 'grammes'),
('Tomate en poudre', 'ml'),
('Beurre frais', 'millilitres'),
('Champignon haché', 'cuillères'),
('Crème séché', 'litres'),
('Oignon bio', 'millilitres'),
('Épinard entier', 'cuillères'),
('Riz haché', 'grammes'),
('Beurre en poudre', 'ml'),
('Lait râpé', 'cuillères'),
('Poisson bio', 'litres'),
('Farine entier', 'tasses'),
('Ail haché', 'ml'),
('Farine séché', 'grammes'),
('Riz râpé', 'tasses'),
('Poivre séché', 'cuillères'),
('Farine frais', 'grammes'),
('Pomme séché', 'cuillères'),
('Thon râpé', 'litres'),
('Noix frais', 'tasses'),
('Riz bio', 'litres'),
('Noix', 'millilitres'),
('Ail bio', 'unités'),
('Poulet haché', 'grammes'),
('Tomate haché', 'grammes'),
('Boeuf haché', 'kg'),
('Noix râpé', 'cuillères'),
('Carotte haché', 'cuillères'),
('Sel en poudre', 'unités'),
('Épinard', 'tasses'),
('Poulet en poudre', 'cuillères'),
('Ail râpé', 'cuillères'),
('Tomate bio', 'kg'),
('Thon râpé', 'ml'),
('Pomme râpé', 'tasses'),
('Noix séché', 'tasses'),
('Poulet en poudre', 'ml'),
('Huile d''olive séché', 'unités'),
('Carotte bio', 'kg'),
('Citron', 'cuillères'),
('Oignon entier', 'cuillères'),
('Sucre frais', 'ml'),
('Pomme en poudre', 'unités'),
('Épinard', 'unités'),
('Boeuf entier', 'ml'),
('Pomme séché', 'tasses'),
('Thon séché', 'cuillères'),
('Crème séché', 'cuillères'),
('Épinard séché', 'millilitres'),
('Tomate haché', 'cuillères'),
('Crème en poudre', 'cuillères'),
('Riz entier', 'ml'),
('Carotte râpé', 'grammes'),
('Carotte haché', 'unités'),
('Beurre entier', 'tasses'),
('Épinard entier', 'kg'),
('Pomme bio', 'unités'),
('Sel', 'unités'),
('Sucre en poudre', 'cuillères'),
('Thon bio', 'grammes'),
('Thon bio', 'grammes'),
('Riz râpé', 'litres'),
('Tomate entier', 'kg'),
('Tomate', 'millilitres'),
('Farine haché', 'litres'),
('Crème séché', 'grammes'),
('Noix entier', 'millilitres'),
('Thon bio', 'millilitres'),
('Pomme séché', 'cuillères'),
('Poisson frais', 'cuillères'),
('Thon séché', 'unités'),
('Carotte frais', 'cuillères'),
('Dinde frais', 'ml'),
('Poisson entier', 'grammes'),
('Banane en poudre', 'grammes'),
('Oignon haché', 'unités'),
('Poulet', 'tasses'),
('Citron bio', 'cuillères'),
('Tomate frais', 'ml'),
('Épinard séché', 'grammes'),
('Sel séché', 'tasses'),
('Thon haché', 'millilitres'),
('Sucre séché', 'millilitres'),
('Dinde bio', 'unités'),
('Lait bio', 'unités'),
('Noix séché', 'unités'),
('Pomme entier', 'ml'),
('Farine haché', 'cuillères'),
('Persil râpé', 'grammes'),
('Riz haché', 'unités'),
('Noix bio', 'grammes'),
('Boeuf séché', 'ml'),
('Épinard', 'tasses'),
('Persil frais', 'litres'),
('Ail frais', 'unités'),
('Farine séché', 'tasses'),
('Boeuf frais', 'litres'),
('Beurre frais', 'grammes'),
('Poivre bio', 'ml'),
('Persil râpé', 'tasses'),
('Citron bio', 'litres'),
('Tomate', 'ml'),
('Farine râpé', 'tasses'),
('Poivre bio', 'cuillères'),
('Riz entier', 'unités'),
('Huile d''olive entier', 'ml'),
('Poivre en poudre', 'litres'),
('Lait haché', 'unités'),
('Riz', 'ml'),
('Poulet frais', 'grammes'),
('Crème', 'kg'),
('Banane', 'ml'),
('Noix haché', 'ml'),
('Poisson', 'kg'),
('Pâtes bio', 'litres'),
('Poivre en poudre', 'cuillères'),
('Citron', 'millilitres'),
('Boeuf haché', 'litres'),
('Persil râpé', 'grammes'),
('Persil râpé', 'tasses'),
('Poulet', 'grammes'),
('Sel entier', 'millilitres'),
('Épinard en poudre', 'tasses'),
('Beurre frais', 'cuillères'),
('Crème', 'millilitres'),
('Carotte en poudre', 'kg'),
('Boeuf haché', 'tasses'),
('Tomate haché', 'ml'),
('Poivre frais', 'unités'),
('Sucre séché', 'kg'),
('Poivre bio', 'cuillères'),
('Thon entier', 'ml'),
('Sel râpé', 'ml'),
('Pâtes râpé', 'litres'),
('Ail en poudre', 'litres'),
('Lait bio', 'unités'),
('Citron', 'kg'),
('Boeuf séché', 'grammes'),
('Persil séché', 'kg'),
('Farine entier', 'tasses'),
('Lait entier', 'unités'),
('Huile d''olive', 'unités'),
('Poulet haché', 'unités'),
('Poisson en poudre', 'litres'),
('Huile d''olive haché', 'litres'),
('Pâtes en poudre', 'tasses'),
('Épinard râpé', 'ml'),
('Champignon séché', 'cuillères'),
('Poivre haché', 'unités'),
('Huile d''olive séché', 'litres'),
('Poulet frais', 'ml'),
('Tomate râpé', 'cuillères'),
('Lait entier', 'ml'),
('Carotte frais', 'unités'),
('Noix en poudre', 'ml'),
('Beurre entier', 'litres'),
('Champignon bio', 'litres'),
('Sucre bio', 'unités'),
('Persil entier', 'unités'),
('Riz', 'cuillères'),
('Oignon frais', 'ml');